import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="px-4">
      <Head>
        <title>Geoguessr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full min-h-screen py-4 flex flex-col flex-1 items-center justify-around bg-gradient-to-tr from-sky-900 to-indigo-900">
        <h1 className="text-3xl font-bold underline">
            Geoguessr by dev3!
        </h1>
        <Link href="/game">
            <button className="border-none bg-green-600 rounded-xl font-bold h-[2rem] px-12 transition hover:scale-110 hover:bg-green-500">
                Play
            </button>
        </Link>
      </main>
    </div>
  )
}
